import os
import pandas as pd

# Generates an oldFile,newFile csv for the impact data

# Path of the generated csv
output_path = './copyFiles/fileChecks/IMPACT.csv'
# Path of oldFile
# The files that need to be renamed are prefixed with "coincident_TES_PMT_"
oldfile_path = '/nfs/slac/g/supercdms/tf/northwestern/AnimalData/AR70/processing_coinc_v0701/'
# Path of newFile
newfile_path = '/gpfs/slac/staas/fs1/supercdms/data/CDMS/Animal/R70/Processed/Releases/ProdCoinc0701/Merged/'
# Site ID
ID = '27'
# Prefix of data files
prefix = 'coincident_TES_PMT_'
# Data file extension
ext = 'pkl'

# Generates the oldfile name
# def oldfile(tes):
#    return oldfile_path + str(tes) + '.pkl'

# Generates the newfile name
def newfile(prefix, ext, oldfile_name):
    # Remove the prefix and extension
    notseries = oldfile_name[len(prefix):-len('.' + ext)]
    
    # IDyymmdd_hhmmss
    # Convert to string
    notseries = str(notseries)
    series = ID + notseries[2:8] + '_' + notseries[8:]
    return series + '.' + ext

# Generates a list of [oldfile,newfile] for each file in the dirrectory.
# Recursive, only renames the files on the top level.
# oldpath = Path of directory to copy from
# newpath = Path of directory to copy to
# toplevel = True if this is the starting dirrectory of the copy (Boolean)
def generate_filelist(oldpath, newpath, toplevel=True):
    filelist = [] # The Filelist that is generated by this function
    dirlist = os.listdir(oldpath)
    for i in dirlist:
        path = os.path.join(oldpath, i)
        if os.path.isdir(path):
            # Generate a list for the sub-directory, and add it to this list
            filelist = filelist + generate_filelist(path, os.path.join(newpath, i), False)
        # end if
        else:
            # Rename files that are in the top level
            if toplevel:
                filelist.append([path, os.path.join(newpath, newfile(prefix, ext, i))])
            else:
                filelist.append([path, os.path.join(newpath, i)])
            # end if
        # end if
    # end for
    return filelist

# Create filelist and turn it into a DataFrame
df = pd.DataFrame(generate_filelist(oldfile_path, newfile_path), columns=['OldFile', 'NewFile'])
df.to_csv(output_path)

# Notify user that operation is completed
print("csv file generation complete")